### ISSUE TITLE
How to prepare data

### ISSUE THREAD

**Issue by muammar** [aksub99/molecular-vae#30]
Hi, thanks for putting this together. In your notebook with an example, I see that you are using the dataset you already processed. I wondered if you could list what the procedure to follow is. I would like to use your implementation. 

Best,

**Comment by aksub99** [comment]
Hi @muammar thanks for your question! Preprocessing was done using the `preprocess.py` script from [https://github.com/maxhodak/keras-molecules](https://github.com/maxhodak/keras-molecules). Let me know if you have any other questions!

**Comment by muammar** [comment]
> Hi @muammar thanks for your question! Preprocessing was done using the `preprocess.py` script from https://github.com/maxhodak/keras-molecules. Let me know if you have any other questions!

Thanks for your reply @aksub99 ! I tried using the repo you posted above and I get this error: 

```
Traceback (most recent call last):
  File "preprocess.py", line 86, in <module>
    main()
  File "preprocess.py", line 59, in main
    h5f.create_dataset('charset', data = charset)
  File "/home/elkhatim/miniconda3/envs/py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/elkhatim/miniconda3/envs/py38/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1717, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U1')
```

I am asking you because it seems to me that `keras-molecules` is kind of abandoned... I wondered if you had any idea about this `TypeError`?

Best,

**Comment by aksub99** [comment]
I actually remember getting the same error when I had used the code. I can't recall exactly how I fixed it but I vaguely remember that in lines 35 and 38 of `preprocess.py`, I had made some simple typecasting fixes. So, I'd direct you towards those lines. Hope this helps!
